"""add_settings_table

Revision ID: 46695d23fc3b
Revises: 4b0adedb7cb4
Create Date: 2025-08-29 23:21:11.567385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46695d23fc3b'
down_revision = '4b0adedb7cb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('setting_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('setting_name')
    )
    op.create_index(op.f('ix_settings_setting_name'), 'settings', ['setting_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_setting_name'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
