"""add_user_activation_fields

Revision ID: 802460aee558
Revises: f0b7ffc0a54f
Create Date: 2025-08-30 19:42:07.083138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802460aee558'
down_revision = 'f0b7ffc0a54f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
