"""add_user_activation_fields

Revision ID: f0b7ffc0a54f
Revises: 46695d23fc3b
Create Date: 2025-08-30 18:12:14.300036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b7ffc0a54f'
down_revision = '46695d23fc3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('activation_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_activation_token'), 'users', ['activation_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_activation_token'), table_name='users')
    op.drop_column('users', 'activation_token_expires')
    op.drop_column('users', 'activation_token')
    # ### end Alembic commands ###
